# Based on the issue template
name: Bug report
description: Create a report to help us improve
title: "[BUG] <title>"
labels: [Bug]
body:
  - type: markdown
    attributes:
      value: |
# DEPRECATION NOTICE 
This image is deprecated. We will not offer support for this image and it will not be updated.


These images were originally created for Apache Guacamole-based Webtop, but since transitioning to an in house web-native protocol, they are no longer maintained. RDP users should seek alternatives while others are advised to transition to [Webtop](https://github.com/linuxserver/docker-webtop).
