#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# default file copies first run
if [[ ! -f /config/.config/openbox/menu.xml ]]; then
    mkdir -p /config/.config/openbox && \
    cp /defaults/menu.xml /config/.config/openbox/menu.xml && \
    lsiown -R abc:abc /config/.config
fi
